### PR TITLE
Added Google Colab notebook

### PR DESCRIPTION
**Pull request by AdamMiltonBarker**
- Fixed typos, file names and formatting
- Added Google Colab notebook and GPU results
- Rounded Google Colab results
- Cleaned up function descriptions

### CODE REVIEW

**Review by rishabhbanga — APPROVED** [review]
Looks good to me. Only changes to be made are in the AutoPilot.md
Change Timediff to TimeDiff

**Comment by AdamMiltonBarker** [comment]
@rishabhbanga  ok thanks will update. Were you able to test the code ?

**Comment by rishabhbanga** [comment]
No, facing this issue:

FileNotFoundError                         Traceback (most recent call last)
<ipython-input-5-d624f6453c0f> in <module>()
----> 1 with open(root_dir + 'Model/config.json') as confs:
      2     confs = json.loads(confs.read())
      3 
      4 print(json.dumps(confs, indent=4, sort_keys=True))

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/My Drive/ALL-Detection-System-2020/Model/config.json'

**Review by rishabhbanga — COMMENTED** [review]
Under Load and print configs:
Change with open(root_dir + '/Model/config.json') as confs:
to with open(root_dir + 'CNN/Model/config.json') as confs:

Also might as well add in the section above it:
cd /content/drive/My Drive/
!git clone -b "0.0.2" https://github.com/AMLResearchProject/ALL-Detection-System-2020.git

Under Sorting Data Section:
Shape is coming as (0,)

ValueError: Found array with 0 sample(s) (shape=(0, 1)) while a minimum of 1 is required.

**Pull request merged**
